# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates Brakeman with GitHub's Code Scanning feature
# Brakeman is a static analysis security vulnerability scanner for Ruby on Rails applications
# For more information see: https://brakemanscanner.org

name: Brakeman Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '40 19 * * 6'

permissions:
  contents: read

jobs:
  brakeman-scan:
    permissions:
      contents: read
      security-events: write
    name: Brakeman Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      # Customize the ruby version depending on your needs
      - name: Setup Ruby
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4
        with:
          ruby-version: '3.2.0'
      - name: Setup Brakeman
        env:
          BRAKEMAN_VERSION: '4.10'
        run: |
          gem install brakeman --version $BRAKEMAN_VERSION
