name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: setup-rails/setup-rails@v1
        with:
          ruby-version: 3.1.3
          yarn-version: 1.22.19
          bundler-cache: true
      - run: bundle exec rails db:create db:migrate db:seed
      - run: bundle exec rails test
