name: Codecov
on: [push, pull_request]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      - uses: codecov/codecov-action@v1
        with:
          flags: unit
          name: codecov
          fail_ci_if_error: true
