name: Codecov Analysis
on: [push, pull_request]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          flags: unittests
          name: codecov-umbrella
          verbose: true
          ruby-version: 3.1.3
          bundler-cache: true
